pim_eikona_tessa_connector:
    settings:
        base_url:
            value: ~
            scope: app
        ui_url:
            value: ~
            scope: app
        username:
            value: ~
            scope: app
        api_key:
            value: ~
            scope: app
        system_identifier:
            value: ~
            scope: app
