parameters:
    eikona.tessa.connector.provider.field.mam.class: Eikona\Tessa\ConnectorBundle\Enrich\Provider\Field\MamFieldProvider


services:
    eikona.tessa:
        class: 'Eikona\Tessa\ConnectorBundle\Tessa'
        arguments:
            - '@oro_config.global'
            - '@pim_serializer'
            - '@kernel'
            - '@logger'
            - '@pim_catalog.repository.product_model'
            - '@eikona.utilities.id_prefixer'
    eikona.utilities.math:
        class: Eikona\Tessa\ConnectorBundle\Utilities\Math
    eikona.utilities.id_prefixer:
        class: Eikona\Tessa\ConnectorBundle\Utilities\IdPrefixer
    eikona.tessa.connector.provider.field.mam:
        class: %eikona.tessa.connector.provider.field.mam.class%
        tags:
            - { name: pim_enrich.provider.field, priority: 90 }
    eikona.tessa.auth_guard:
        class: 'Eikona\Tessa\ConnectorBundle\Security\AuthGuard'
        arguments:
            - '@eikona.tessa'
            - '@eikona.utilities.math'
            - '@logger'

    eikona.tessa.serializer.normalizer.attribute:
        class: Eikona\Tessa\ConnectorBundle\Extension\Normalizer\Standard\AttributeNormalizer
        arguments:
            - '@pim_catalog.normalizer.standard.translation'
            - '@pim_catalog.normalizer.standard.datetime'
            - '@request_stack'
        tags:
            - { name: pim_serializer.normalizer, priority: 91 }


    eikona.tessa.serializer.normalizer.product_properties:
        class: Eikona\Tessa\ConnectorBundle\Extension\Normalizer\Standard\ProductPropertiesNormalizer
        arguments:
            - '@pim_catalog.normalizer.standard.product'
            - '@pim_api.repository.attribute'
            - '@router'
            - '@request_stack'
            - '@eikona.utilities.id_prefixer'
        tags:
            - { name: pim_serializer.normalizer, priority: 91 }
    eikona.tessa.serializer.normalizer.channel:
        class: Eikona\Tessa\ConnectorBundle\Extension\Normalizer\Standard\ChannelNormalizer
        parent: pim_catalog.normalizer.standard.channel
        arguments:
            - '@request_stack'
        tags:
            - { name: pim_serializer.normalizer, priority: 91 }

    eikona.tessa.serializer.normalizer.category:
        class: Eikona\Tessa\ConnectorBundle\Extension\Normalizer\Standard\CategoryNormalizer
        arguments:
            - '@pim_catalog.normalizer.standard.translation'
            - '@request_stack'
        tags:
            - { name: pim_serializer.normalizer, priority: 91 }
